//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriFarmProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBidder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBidder()
        {
            this.tblBanks = new HashSet<tblBank>();
            this.tblBiddings = new HashSet<tblBidding>();
            this.tblSales = new HashSet<tblSale>();
        }
    
        public int BidderId { get; set; }
        public string BidderName { get; set; }
        public string BidderContactNo { get; set; }
        public string BidderEmail { get; set; }
        public string BidderAddress { get; set; }
        public string BidderCity { get; set; }
        public string BidderState { get; set; }
        public string BidderPincocde { get; set; }
        public string BidderAadhar { get; set; }
        public string BidderPAN { get; set; }
        public string BidderTradeLicense { get; set; }
        public string BidderPassword { get; set; }
        public Nullable<bool> BidderApproved { get; set; }
        public Nullable<int> ApprovalAdminId { get; set; }
    
        public virtual tblAdmin tblAdmin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBank> tblBanks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBidding> tblBiddings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSale> tblSales { get; set; }
    }
}
