//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriFarmProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBidding
    {
        public int BiddingId { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<int> BidderId { get; set; }
        public Nullable<int> InitialPrice { get; set; }
        public Nullable<int> CurrentBidPrice { get; set; }
        public Nullable<int> PreviousBidPrice { get; set; }
        public Nullable<System.DateTime> BidCloseTime { get; set; }
        public Nullable<int> ApprovalAdminId { get; set; }
    
        public virtual tblAdmin tblAdmin { get; set; }
        public virtual tblBidder tblBidder { get; set; }
        public virtual tblCropRequest tblCropRequest { get; set; }
    }
}
