//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriFarmProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSale
    {
        public int SalesId { get; set; }
        public Nullable<int> FarmerId { get; set; }
        public Nullable<int> BidderId { get; set; }
        public string CropName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> MinSalePrice { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public Nullable<int> SoldPrice { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> ApprovalAdminId { get; set; }
    
        public virtual tblAdmin tblAdmin { get; set; }
        public virtual tblBidder tblBidder { get; set; }
        public virtual tblFarmer tblFarmer { get; set; }
    }
}
