
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AgriFarmProj.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblContactU
{

    public int RequestToken { get; set; }

    public string Email { get; set; }

    public string ContactName { get; set; }

    public string RequestType { get; set; }

    public string message { get; set; }

    public string status { get; set; }

    public Nullable<int> ApprovalAdminId { get; set; }



    public virtual tblAdmin tblAdmin { get; set; }

}

}
