
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AgriFarmProj.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblFarmLand
{

    public int FarmerLandId { get; set; }

    public Nullable<int> FarmerId { get; set; }

    public string FarmerLandArea { get; set; }

    public string FarmerLandAddress { get; set; }

    public string FarmerLandPincode { get; set; }



    public virtual tblFarmer tblFarmer { get; set; }

}

}
