
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AgriFarmProj.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblInsuranceClaim
{

    public int CliamId { get; set; }

    public Nullable<int> PolicyNo { get; set; }

    public string CauseOfClaim { get; set; }

    public Nullable<System.DateTime> DateOfLoss { get; set; }

    public Nullable<System.DateTime> DateOfClaim { get; set; }

    public Nullable<int> AmountClaimed { get; set; }

    public string ApprovalStatus { get; set; }

    public Nullable<int> ApprovalAdminId { get; set; }



    public virtual tblAdmin tblAdmin { get; set; }

    public virtual tblInsurance tblInsurance { get; set; }

}

}
