
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AgriFarmProj.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblInsurance
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblInsurance()
    {

        this.tblInsuranceClaims = new HashSet<tblInsuranceClaim>();

    }


    public int PolicyNo { get; set; }

    public Nullable<int> FarmerId { get; set; }

    public string CompanyName { get; set; }

    public string Season { get; set; }

    public string Year { get; set; }

    public string Crop { get; set; }

    public Nullable<int> SumInsured { get; set; }

    public Nullable<System.DateTime> DateOfInsurance { get; set; }

    public Nullable<decimal> Area { get; set; }

    public Nullable<int> ApprovalAdminId { get; set; }



    public virtual tblAdmin tblAdmin { get; set; }

    public virtual tblFarmer tblFarmer { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblInsuranceClaim> tblInsuranceClaims { get; set; }

}

}
